print("Hello World")
print(10+5)
print("Hello This is Automatically Triggeredd By the Jenkins")
print("My Name  Is Ayush Singh")
print("Ankit Singh Is My Bestffriend And currently he is working as a java Developer In HCL Technology")
